[tool.poetry]
name = "go-protoc-yamllint"
version = "0.1.0"
description = "python site packages with yamllint"
authors = ["wasilibs authors"]

[tool.poetry.dependencies]
python = "~3.12"
yamllint = "^1.35.1"
