name: CI
on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-15
          - ubuntu-24.04
          - windows-2025
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - uses: curioswitch/go-build/.github/actions/setup-go@7489f72867246693fc1cc65560c68cdc860a1f8a # v0.5.2

      - name: run lints
        if: startsWith(matrix.os, 'ubuntu-')
        run: go run ./build lint

      - name: run tests
        run: go run ./build test

      - name: build snapshot
        if: startsWith(matrix.os, 'ubuntu-')
        run: go run ./build snapshot
