name: "Release"

on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Release
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0

      - uses: curioswitch/go-build/.github/actions/setup-go@7489f72867246693fc1cc65560c68cdc860a1f8a # v0.5.2

      - run: go run ./build release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
